### ISSUE TITLE
Is there any conflict with Laravel 8?

### ISSUE THREAD

**Issue by tiaoricardo** [tailwindlabs/tailwindcss-forms#23] opened 2020-12-04 20:31 UTC
I am trying styling a form and all borders of inputs are hidden and that isn't default behavior for them.
![Screenshot](https://user-images.githubusercontent.com/852439/101211824-87e5be00-3656-11eb-8613-0095a57c4438.png)

**Comment by AKopelevich** [comment] 2020-12-08 08:37
Could you provide the source code of this screen, so we could try to help you?

**Comment by SquareBeard** [comment] 2021-01-02 17:25
Adding the "border" class on the input should fix this.

**Comment by RobinMalfait** [comment] 2021-02-26 11:01
Hey! Thank you for your question!
Much appreciated! 🙏

There should be any conflicts with Laravel.
That said, make sure to validate the following things:
- Did you require the plugin in your config?
- Did you restart your build?
- Do you have other styles overriding it?
- Do you have a `type="text"` available on the element?

Can you try and reproduce it on https://play.tailwindcss.com and share it?

**Comment by clmntgr** [comment] 2021-03-04 13:01
Hello @RobinMalfait,
I have the same issue but I can't reproduce it on Tailwind Play (here is a link with my config and an example https://play.tailwindcss.com/fwGUr2EWo1).

Here is the CSS I'm getting locally
![image](https://user-images.githubusercontent.com/6172122/109967422-b0cb2d00-7cf1-11eb-91a4-8729695d429b.png)

As you can see there is no `border-width`, I don't know why as I'm not overriding this property in my config.
It's not a big deal for me as I will override that style anyway, but maybe it can help for the debugging.

**Comment by clmntgr** [comment] 2021-03-04 13:21
Ok I find the issue, I'm on Tailwind v1.9.6 and it's only working on Tailwind v2, @tiaoricardo are you using Tailwind V2?

**Comment by adamwathan** [comment] 2021-03-26 02:21
Closing since OP hasn't provided a reproduction and sounds like it's likely a v1 vs v2 thing as mentioned. Feel free to open a new issue if still need help!

**Closed by adamwathan** 2021-03-26 02:21 UTC
Labels: Needs more info
